/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import BLL.FichajeOperariosBLL;
import ENTIDAD.FichajeOperarios;
import static ENTIDAD.fecha.DatetoSpanishString;
import datechooser.beans.DateChooserDialog;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import MODELOS.FormatoTabla;
import MODELOS.ModeloTablaFichajeOperariosVista;
import MODELOS.ModeloTablaInformacionOperarioVista;
//PARA LA HORA EN TIEMPO REAL
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author miguel
 */
public class JIntFrmFichajeOperarios extends javax.swing.JInternalFrame implements Runnable{
    /**
     * Creates new form JIntFrmFichajeOperarios
     */
    //RELOJ EN TIEMPO REAL
    int hora, minutos, segundos;
    Calendar calendario;
    Thread h1;
//    private Dimension dim;
    
    
    FichajeOperariosBLL fichajeOperariobll=new FichajeOperariosBLL();
    ArrayList<FichajeOperarios> fichajeOperarios= new ArrayList();
    ArrayList<FichajeOperarios> fichajeOperariosSalida= new ArrayList();
    ArrayList<FichajeOperarios> fichajeOperariosInforme= new ArrayList();
    Date data=new Date();
//    DateFormat hora1=new SimpleDateFormat("HH:mm");
    public JIntFrmFichajeOperarios() throws SQLException {
        
        
                //con esto obtienes en tamano en en x y y de tu monitor

//        dim=super.getToolkit().getScreenSize();
//
//        super.setSize(dim);
//
//
//        super.setVisible(true);
//        
        
        
        //String codigo="";
        
        fichajeOperariosSalida=fichajeOperariobll.obtenerFichajeOperariosSalida();
        fichajeOperarios=fichajeOperariobll.obtenerFichajeOperarios();
        //fichajeOperariosInforme=fichajeOperariobll.obtenerFichajeOperariosInforme(codigo);
        initComponents();
        
         
        h1 = new Thread(this);//hilo para el reloj
        h1.start();
            
        jTOperario.setEditable(false);
        jTFecha.setEditable(false);
        jTHora.setEditable(false);
        jBreset.setVisible(true);
        
        //introducción hora
        //jTHora.setText(hora1.format(data));
        //introducción data
        jTFecha.setText(DatetoSpanishString(data));
        
        
        //modificar ancho columnas
        refrescarDimensionesColumna();
//        TableColumnModel columnModel = jTFichajeOperarios.getColumnModel();//modificador columnas tabla operarios entrada
//        TableColumnModel columnModel2 = jTFichajeOperariosSalida.getColumnModel();//modificador columnas tabla operarios salida
//        TableColumnModel columnModel3 = jTInformeOperario.getColumnModel();//modificardor columnas tabla informe operario
//        dimensionesColumnas(columnModel);
//        dimensionesColumnas(columnModel2);
//        dimensionesColumnas2(columnModel3);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTFichajeOperarios = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTFichajeOperariosSalida = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTInformeOperario = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTOperario = new javax.swing.JTextField();
        jTFecha = new javax.swing.JTextField();
        jTHora = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBreset = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setAutoscrolls(true);

        jTFichajeOperarios.setBorder(new javax.swing.border.MatteBorder(null));
        jTFichajeOperarios.setModel(new ModeloTablaFichajeOperariosVista(fichajeOperarios));
        jTFichajeOperarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFichajeOperariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTFichajeOperarios);

        jTFichajeOperariosSalida.setModel(new ModeloTablaFichajeOperariosVista(fichajeOperariosSalida));
        jTFichajeOperariosSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFichajeOperariosSalidaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTFichajeOperariosSalida);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OPERARIOS DENTRO");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("OPERARIOS FUERA");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(151, 17));
        jLabel2.setMinimumSize(new java.awt.Dimension(151, 17));
        jLabel2.setPreferredSize(new java.awt.Dimension(151, 17));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CONTROL OPERARIOS");

        jTInformeOperario.setModel(new ModeloTablaInformacionOperarioVista(fichajeOperariosInforme));
        jScrollPane3.setViewportView(jTInformeOperario);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("INFROMACIÓN OPERARIO ");

        jTFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFechaMouseClicked(evt);
            }
        });

        jLabel5.setText("HORA");

        jLabel6.setText("FECHA");

        jBreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/actualizar.jpg"))); // NOI18N
        jBreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(jTOperario, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(596, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBreset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTHora, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBreset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTOperario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFichajeOperariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFichajeOperariosMouseClicked
        
        int row=jTFichajeOperarios.getSelectedRow();//nº fila seleccionada
        //int col=jTFichajeOperarios.getSelectedColumn();//nº columna seleccionada
        String codigo="";
        String nombre="";
        String fecha="";
        fecha=(jTFecha.getText());
        
        /***********************************************************/
        //CONVERTIR 
        Date data; 
        data=convertir_String_Date(fecha);
        
        
        
        
        /*******************************************************/
        codigo=(String.valueOf(jTFichajeOperarios.getModel().getValueAt(row,0)));//devuelve el valor de la celda seleccionada
        nombre=(String.valueOf(jTFichajeOperarios.getModel().getValueAt(row,1)));


        jTOperario.setText(codigo+" - "+nombre);
        try {
            //System.out.println(codigo);
            fichajeOperariosInforme=fichajeOperariobll.obtenerFichajeOperariosInforme(codigo,data);
        } catch (SQLException ex) {
            Logger.getLogger(JIntFrmFichajeOperarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

        jTInformeOperario.setModel(new ModeloTablaInformacionOperarioVista(fichajeOperariosInforme));//introducir contenido en la tabla jTInformeOperario
        TableColumnModel columnModel3 = jTInformeOperario.getColumnModel();//modificardor columnas tabla informe operario
        dimensionesColumnas2(columnModel3);
        jTInformeOperario.setDefaultRenderer (Object.class, new FormatoTabla());//introducir color al fondo del las celdas vacías
                

//vaciarTabla();
        //colorColumna(row);//COLOR DE COLUMNA
        //cambiarTextoColumna(row);
//cambiar color fondo //jTInformeOperario.setBackground(Color.red);
    }//GEN-LAST:event_jTFichajeOperariosMouseClicked

    private void jTFichajeOperariosSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFichajeOperariosSalidaMouseClicked
        int row=jTFichajeOperariosSalida.getSelectedRow();//nº fila seleccionada
        //int col=jTFichajeOperarios.getSelectedColumn();//nº columna seleccionada
        String codigo="";
        String nombre="";
        String fecha="";
        fecha=(jTFecha.getText());
        codigo=(String.valueOf(jTFichajeOperariosSalida.getModel().getValueAt(row,0)));//devuelve el valor de la celda seleccionada
        nombre=(String.valueOf(jTFichajeOperariosSalida.getModel().getValueAt(row,1)));


        jTOperario.setText(codigo+" - "+nombre);
        //System.out.println(codigo);
        
        try {
            //System.out.println(codigo);
            fichajeOperariosInforme=fichajeOperariobll.obtenerFichajeOperariosInforme(codigo,data);
        } catch (SQLException ex) {
            Logger.getLogger(JIntFrmFichajeOperarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

        jTInformeOperario.setModel(new ModeloTablaInformacionOperarioVista(fichajeOperariosInforme));//introducir contenido en la tabla jTInformeOperario
        TableColumnModel columnModel3 = jTInformeOperario.getColumnModel();//modificardor columnas tabla informe operario
        dimensionesColumnas2(columnModel3);
        jTInformeOperario.setDefaultRenderer (Object.class, new FormatoTabla());//introducir color al fondo del las celdas vacías
    }//GEN-LAST:event_jTFichajeOperariosSalidaMouseClicked

    private void jBresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBresetActionPerformed
        try {
            //Object nuevo[]= {temp.getRowCount()+1,"",""};
//temp.addRow(nuevo);
        fichajeOperariosSalida=fichajeOperariobll.obtenerFichajeOperariosSalida();
        fichajeOperarios=fichajeOperariobll.obtenerFichajeOperarios();
        fichajeOperariosInforme=fichajeOperariobll.obtenerFichajeOperariosInforme(null,data);
        
        } catch (SQLException ex) {
            Logger.getLogger(JIntFrmFichajeOperarios.class.getName()).log(Level.SEVERE, null, ex);
        }

        jTFichajeOperarios.setModel(new ModeloTablaFichajeOperariosVista(fichajeOperarios));
        jTFichajeOperariosSalida.setModel(new ModeloTablaFichajeOperariosVista(fichajeOperariosSalida));
        jTInformeOperario.setModel(new ModeloTablaInformacionOperarioVista(fichajeOperariosInforme));
        jTOperario.setText("");
        refrescarDimensionesColumna();
       // ModeloTablaFichajeOperariosVista temp = (ModeloTablaFichajeOperariosVista) jTInformeOperario.getModel();
//        Object row[]= {"","","",""};
//        temp.addRow(row);
    }//GEN-LAST:event_jBresetActionPerformed

    private void jTFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFechaMouseClicked
datechooser.beans.DateChooserCombo dateChooserCombo1 = new datechooser.beans.DateChooserCombo();       

//DateChooserDialog dt = new DateChooserDialog();
       //dt.showDialog(null);
       //dateChooserDialog1.showDialog(null);
    }//GEN-LAST:event_jTFechaMouseClicked
//AL PRESIONAR LA TECLA ENTER
    public void keyPressed(KeyEvent ke) {
              if (ke.getKeyCode() == KeyEvent.VK_ENTER) {
                  System.out.println(jTFecha.getText());
              }
          }
    
    
    /**
     * @param args the command line arguments
     */
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JIntFrmFichajeOperarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JIntFrmFichajeOperarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JIntFrmFichajeOperarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JIntFrmFichajeOperarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JIntFrmFichajeOperarios().setVisible(true);
//            }
//        });
//    }
  
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFecha;
    private javax.swing.JTable jTFichajeOperarios;
    private javax.swing.JTable jTFichajeOperariosSalida;
    private javax.swing.JTextField jTHora;
    private javax.swing.JTable jTInformeOperario;
    private javax.swing.JTextField jTOperario;
    // End of variables declaration//GEN-END:variables
  static void dimensionesColumnas(TableColumnModel columnModel){
              
    /*redimensionar 1 columna de la tabla
        TableColumn columna = jTFichajeOperarios.getColumn("OPERARIO");
        columna.setMinWidth(ancho);
       
       redimensionar todas las columnas

       columnModel.getColumn(0).setPreferredWidth(100);
    */     
        columnModel.getColumn(0).setMinWidth(50);
        columnModel.getColumn(0).setMaxWidth(65);
        columnModel.getColumn(1).setMinWidth(260);
        columnModel.getColumn(2).setMinWidth(200);
        columnModel.getColumn(3).setMinWidth(80);
        columnModel.getColumn(4).setMinWidth(70);

  
  }
  static void dimensionesColumnas2(TableColumnModel columnModel){
        columnModel.getColumn(0).setMinWidth(200);
        columnModel.getColumn(1).setMinWidth(40);
        columnModel.getColumn(2).setMinWidth(10);
        //columnModel.getColumn(2).setPreferredWidth(20);


  
  
  }
//RELOJ TIEMPO REAL
 @Override
    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == h1) {
            calcula();
            jTHora.setText(hora + ":" + minutos + ":" + segundos);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }
    public void calcula() {
        Calendar calendario = new GregorianCalendar();
        hora =calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND);
    }
//    public void refrescarTablas(){
//     jTFichajeOperariosSalida.setModel(ModeloTablaFichajeOperariosVista);
//     ModeloTablaFichajeOperariosVista.fireTableDataChanged();
//    
//    }
// 
    public void colorColumna(int row){
        String valor="";
        valor=(String.valueOf(jTFichajeOperarios.getModel().getValueAt(row,2)));//devuelve el valor de la celda seleccionada
        if(valor=="S"){
            jTInformeOperario.setBackground(Color.YELLOW);
        }
//        jTInformeOperario.setDefaultRenderer (Object.class, new FormatoTabla());
//        jTInformeOperario.setSelectionForeground(Color.lightGray);
        //jTInformeOperario.setBackground(Color.red);
    
    }
    public void cambiarTextoColumna(int row){
        if(String.valueOf(jTInformeOperario.getValueAt(row,2)).equals("S")){            
            jTInformeOperario.setValueAt("SALIDA", row, 2);
        }
    
    }
    public void refrescarDimensionesColumna(){
        TableColumnModel columnModel = jTFichajeOperarios.getColumnModel();//modificador columnas tabla operarios entrada
        TableColumnModel columnModel2 = jTFichajeOperariosSalida.getColumnModel();//modificador columnas tabla operarios salida
        TableColumnModel columnModel3 = jTInformeOperario.getColumnModel();//modificardor columnas tabla informe operario
        dimensionesColumnas(columnModel);
        dimensionesColumnas(columnModel2);
        dimensionesColumnas2(columnModel3);
    
    
    }
    public Date convertir_String_Date(String data){
            SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yyyy");
//            String strFecha = "2007-12-25";
            Date fecha = null;
            try {

                fecha = formatoDelTexto.parse(data);

            } catch (ParseException ex) {

                ex.printStackTrace();

            }

//    System.out.println(fecha.toString());
        return fecha;
    }
    
    
}
