/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import BLL.ArticuloBLL;
import BLL.ClienteBLL;
import BLL.OrdenBLL;
import BLL.UsuarioBLL;
import ENTIDAD.Articulo;
import ENTIDAD.Cliente;
import ENTIDAD.Orden;
import ENTIDAD.Usuario;
import java.awt.BorderLayout;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Informatica
 */
public class JIntFrmCrearPalets extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIntFrmNuevaOrdInterna
     */
    public JIntFrmCrearPalets() throws SQLException {
        initComponents();
        cargarCBClientes();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jTabbedCrearPalets = new javax.swing.JTabbedPane();
        jPanelPaletSeccional = new javax.swing.JPanel();
        jCBClienteSec = new javax.swing.JComboBox();
        jCBArticulosSec = new javax.swing.JComboBox();
        jTFCantidadPaletsSec = new javax.swing.JTextField();
        jButtonCrearSec = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCBFormatoPalet = new javax.swing.JComboBox();
        jPanelPaletBascualnte = new javax.swing.JPanel();
        jCBClienteBas = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jCBArticulosBAS = new javax.swing.JComboBox();
        jTFCantidadPalets = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCrearBAS = new javax.swing.JButton();

        setTitle("Creación de palets");

        jTabbedCrearPalets.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedCrearPalets.setToolTipText("");
        jTabbedCrearPalets.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedCrearPalets.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCBClienteSec.setToolTipText("");
        jCBClienteSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBClienteSecActionPerformed(evt);
            }
        });

        jCBArticulosSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBArticulosSecActionPerformed(evt);
            }
        });

        jButtonCrearSec.setText("Crear");
        jButtonCrearSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearSecActionPerformed(evt);
            }
        });

        jLabel4.setText("CLIENTE");

        jLabel5.setText("ARTICULO");

        jLabel6.setText("Formato palet");

        jCBFormatoPalet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6", "8", "12" }));

        javax.swing.GroupLayout jPanelPaletSeccionalLayout = new javax.swing.GroupLayout(jPanelPaletSeccional);
        jPanelPaletSeccional.setLayout(jPanelPaletSeccionalLayout);
        jPanelPaletSeccionalLayout.setHorizontalGroup(
            jPanelPaletSeccionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaletSeccionalLayout.createSequentialGroup()
                .addGroup(jPanelPaletSeccionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPaletSeccionalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelPaletSeccionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelPaletSeccionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBArticulosSec, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBClienteSec, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPaletSeccionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCBFormatoPalet, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFCantidadPaletsSec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))))
                    .addGroup(jPanelPaletSeccionalLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jButtonCrearSec, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(500, Short.MAX_VALUE))
        );
        jPanelPaletSeccionalLayout.setVerticalGroup(
            jPanelPaletSeccionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaletSeccionalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelPaletSeccionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBClienteSec, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPaletSeccionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jCBArticulosSec, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPaletSeccionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCBFormatoPalet, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFCantidadPaletsSec, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCrearSec, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );

        jTabbedCrearPalets.addTab("SECCIONAL", jPanelPaletSeccional);

        jCBClienteBas.setToolTipText("");
        jCBClienteBas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBClienteBasActionPerformed(evt);
            }
        });

        jLabel1.setText("CLIENTE");

        jCBArticulosBAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBArticulosBASActionPerformed(evt);
            }
        });

        jLabel2.setText("ARTICULO");

        jLabel3.setText("CANTIDAD PALETS");

        jButtonCrearBAS.setText("Crear");
        jButtonCrearBAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearBASActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPaletBascualnteLayout = new javax.swing.GroupLayout(jPanelPaletBascualnte);
        jPanelPaletBascualnte.setLayout(jPanelPaletBascualnteLayout);
        jPanelPaletBascualnteLayout.setHorizontalGroup(
            jPanelPaletBascualnteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaletBascualnteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPaletBascualnteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelPaletBascualnteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCrearBAS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCantidadPalets, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBClienteBas, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBArticulosBAS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(481, Short.MAX_VALUE))
        );
        jPanelPaletBascualnteLayout.setVerticalGroup(
            jPanelPaletBascualnteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaletBascualnteLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelPaletBascualnteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBClienteBas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelPaletBascualnteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBArticulosBAS, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPaletBascualnteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCantidadPalets, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCrearBAS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(409, Short.MAX_VALUE))
        );

        jTabbedCrearPalets.addTab("BASCULANTE", jPanelPaletBascualnte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedCrearPalets)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedCrearPalets, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cargarCBClientes() throws SQLException{
        ClienteBLL cliBLL=new ClienteBLL();
        jCBClienteBas.removeAllItems();
        ArrayList<Cliente> clientes;
        clientes=cliBLL.listaClientes();
        Iterator it=clientes.iterator();
        while(it.hasNext()){
            Cliente cli=((Cliente)it.next());
            jCBClienteBas.addItem(cli.toString());
            jCBClienteSec.addItem(cli.toString());
        }
    } 
    public void cargarCBArticulosBAS(Cliente cliente) throws SQLException{
        Articulo articulo=new Articulo();
        articulo.setTipologia("GSBAS");
         
        ArticuloBLL opBLL=new ArticuloBLL();
        jCBArticulosBAS.removeAllItems();
        ArrayList <Articulo> articulos;
        articulos=opBLL.listaArticulos(articulo,cliente);
        Iterator it= articulos.iterator();
        while(it.hasNext()){           
           Articulo art=((Articulo)it.next());                   
           jCBArticulosBAS.addItem(art.toString());          
        }
    }
    public void cargarCBArticulosSEC(Cliente cliente) throws SQLException{
        Articulo articulo=new Articulo();
        articulo.setTipologia("GS");
         
        ArticuloBLL opBLL=new ArticuloBLL();
        jCBArticulosSec.removeAllItems();
        ArrayList <Articulo> articulos;
        articulos=opBLL.listaArticulos(articulo,cliente);
        Iterator it= articulos.iterator();
        while(it.hasNext()){           
           Articulo art=((Articulo)it.next());                   
           jCBArticulosSec.addItem(art.toString());          
        }
    }
    private void jCBArticulosBASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBArticulosBASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBArticulosBASActionPerformed

    private void jButtonCrearBASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearBASActionPerformed
        UsuarioBLL usBLL=new UsuarioBLL();
        
        Usuario us=new Usuario();
        try {
            us = usBLL.obtenerUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(JIntFrmNuevaOrdInterna.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        OrdenBLL ordBLL=new OrdenBLL();
        Orden ord=new Orden();
        ord.setSerOrden("S");
        ord.setEstado("Y");
        ord.setTipo("I");
        String articulo=(String) jCBArticulosBAS.getSelectedItem();
        String codigo[]=articulo.split("-");
        
        Articulo art=new Articulo();
        art.setAlias(codigo[0]);
        art.setCodigo(codigo[1]);    
        ord.setUnidades(11);
        ord.setVariablesOrden("\\\\[Ptas%20X%20Palet]:11");
        ord.setArticulo(art);       
        String respuestaOrden="";
        int cantidad=Integer.parseInt(jTFCantidadPalets.getText());
        String cliente=(String) jCBClienteBas.getSelectedItem();
        String codCliente[]=cliente.split("-");
        Cliente cli=new Cliente();
        cli.setCodigo(codCliente[0]);
        try {
            try {       
                
                respuestaOrden = ordBLL.nuevoPalet(ord,us,cli,cantidad);
               
            } catch (InterruptedException ex) {
                Logger.getLogger(JIntFrmNuevaOrdInterna.class.getName()).log(Level.SEVERE, null, ex);
            }
                  
            JOptionPane.showMessageDialog(null,respuestaOrden, "Orden Creada", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
             JOptionPane.showMessageDialog(this, ex, "ERROR", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(JIntFrmNuevaOrdInterna.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonCrearBASActionPerformed

    private void jCBClienteBasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBClienteBasActionPerformed
        String cliente=(String) jCBClienteBas.getSelectedItem();
        String codCliente[]=cliente.split("-");
        Cliente cli=new Cliente();
        cli.setCodigo(codCliente[0]);
        try {
            cargarCBArticulosBAS(cli);
        } catch (SQLException ex) {
            Logger.getLogger(JIntFrmCrearPalets.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }//GEN-LAST:event_jCBClienteBasActionPerformed

    private void jCBClienteSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBClienteSecActionPerformed
        String cliente=(String) jCBClienteBas.getSelectedItem();
        String codCliente[]=cliente.split("-");
        Cliente cli=new Cliente();
        cli.setCodigo(codCliente[0]);
        try {
            cargarCBArticulosSEC(cli);
        } catch (SQLException ex) {
            Logger.getLogger(JIntFrmCrearPalets.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCBClienteSecActionPerformed

    private void jCBArticulosSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBArticulosSecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBArticulosSecActionPerformed

    private void jButtonCrearSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearSecActionPerformed
       UsuarioBLL usBLL=new UsuarioBLL();
        
        Usuario us=new Usuario();
        try {
            us = usBLL.obtenerUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(JIntFrmNuevaOrdInterna.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        OrdenBLL ordBLL=new OrdenBLL();
        Orden ord=new Orden();
        ord.setSerOrden("S");
        ord.setEstado("Y");
        ord.setTipo("E");
        String articulo=(String) jCBArticulosSec.getSelectedItem();
        String codigo[]=articulo.split("-");
        
        Articulo art=new Articulo();
        art.setAlias(codigo[0]);
        art.setCodigo(codigo[1]);    
        ord.setUnidades(Integer.parseInt(jCBFormatoPalet.getSelectedItem().toString()));
        ord.setArticulo(art);       
        ord.setVariablesOrden("\\\\[Ptas%20X%20Palet]:"+jCBFormatoPalet.getSelectedItem().toString());
        String respuestaOrden="";
        int cantidad=Integer.parseInt(jTFCantidadPaletsSec.getText());
        String cliente=(String) jCBClienteSec.getSelectedItem();
        String codCliente[]=cliente.split("-");
        Cliente cli=new Cliente();
        cli.setCodigo(codCliente[0]);
        try {
            try {       
                
                respuestaOrden = ordBLL.nuevoPalet(ord,us,cli,cantidad);
               
            } catch (InterruptedException ex) {
                Logger.getLogger(JIntFrmNuevaOrdInterna.class.getName()).log(Level.SEVERE, null, ex);
            }
                  
            JOptionPane.showMessageDialog(null,respuestaOrden, "Orden Creada", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
             JOptionPane.showMessageDialog(this, ex, "ERROR", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(JIntFrmNuevaOrdInterna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCrearSecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearBAS;
    private javax.swing.JButton jButtonCrearSec;
    private javax.swing.JComboBox jCBArticulosBAS;
    private javax.swing.JComboBox jCBArticulosSec;
    private javax.swing.JComboBox jCBClienteBas;
    private javax.swing.JComboBox jCBClienteSec;
    private javax.swing.JComboBox jCBFormatoPalet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelPaletBascualnte;
    private javax.swing.JPanel jPanelPaletSeccional;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTFCantidadPalets;
    private javax.swing.JTextField jTFCantidadPaletsSec;
    private javax.swing.JTabbedPane jTabbedCrearPalets;
    // End of variables declaration//GEN-END:variables
}
