/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package VISTA;


import UTILIDADES.ImagenFondo;
import VISTA.JIntFrmArtFichajes;
import VISTA.JIntFrmCrearPalets;
import VISTA.JIntFrmFichajeOperarios;
import VISTA.JIntFrmNuevaOrdInterna;
import java.awt.Graphics;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author vicent
 */
public class MAGUISA extends javax.swing.JFrame {



    /**
     * Creates new form Veterinaria
     */
   
    public MAGUISA() {
        try {
		UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel"); //CAMBIAMOS EL ASPECTO DE LA APLICACION PARA HACERLO MAS AGRADABLE
	} catch (Exception e) {
		e.printStackTrace();
	}
        initComponents();
        /*jMenuItem_ArtFichajes.setVisible(false);
        jMenuItem_NuevaOrden.setVisible(false);
        jMenuItemPalets.setVisible(false);*/
        //jPanelPrincipal.setBorder(new ImagenFondo());
        this.setExtendedState(MAGUISA.MAXIMIZED_BOTH);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanelPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuIxir = new javax.swing.JMenuItem();
        jMenuOrdenes = new javax.swing.JMenu();
        jMenuItem_NuevaOrden = new javax.swing.JMenuItem();
        jMenuItemPalets = new javax.swing.JMenuItem();
        jMenuProduccion = new javax.swing.JMenu();
        jMenuItem_ArtFichajes = new javax.swing.JMenuItem();
        jMenuItem_OperariosActivos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuSobre = new javax.swing.JMenuItem();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(1024, 768));

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ICONOS/folder_full.png"))); // NOI18N
        jMenu1.setText("Archivo");

        jMenuIxir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ICONOS/door-icone-6183-32.png"))); // NOI18N
        jMenuIxir.setText("Salir");
        jMenuIxir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIxirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuIxir);

        jMenuBar1.add(jMenu1);

        jMenuOrdenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ICONOS/page_process.png"))); // NOI18N
        jMenuOrdenes.setText("Ordenes");

        jMenuItem_NuevaOrden.setText("Nueva Orden Fabricacion");
        jMenuItem_NuevaOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NuevaOrdenActionPerformed(evt);
            }
        });
        jMenuOrdenes.add(jMenuItem_NuevaOrden);

        jMenuItemPalets.setText("Creador Palets");
        jMenuItemPalets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPaletsActionPerformed(evt);
            }
        });
        jMenuOrdenes.add(jMenuItemPalets);

        jMenuBar1.add(jMenuOrdenes);

        jMenuProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ICONOS/users.png"))); // NOI18N
        jMenuProduccion.setText("Operarios");

        jMenuItem_ArtFichajes.setText("Articulo Fichajes");
        jMenuItem_ArtFichajes.setToolTipText("");
        jMenuItem_ArtFichajes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuItem_ArtFichajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ArtFichajesActionPerformed(evt);
            }
        });
        jMenuProduccion.add(jMenuItem_ArtFichajes);

        jMenuItem_OperariosActivos.setText("Operarios Activos");
        jMenuItem_OperariosActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_OperariosActivosActionPerformed(evt);
            }
        });
        jMenuProduccion.add(jMenuItem_OperariosActivos);

        jMenuBar1.add(jMenuProduccion);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ICONOS/ayuda.png"))); // NOI18N
        jMenu2.setText("Ayuda");
        jMenu2.setActionCommand("jMAyuda");

        jMenuSobre.setText("Sobre");
        jMenuSobre.setActionCommand("jMiAcercaDe");
        jMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSobreActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuSobre);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuIxirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIxirActionPerformed
        // TODO add your handling code here:
        int opc = JOptionPane.showConfirmDialog(this, "Estas seguro de que quieres salir?","Eixir",JOptionPane.YES_NO_OPTION);
            //JOptionPane.showMessageDialog(this, opc);
            if(opc==JOptionPane.YES_OPTION){
                System.exit(0);
            }
    }//GEN-LAST:event_jMenuIxirActionPerformed

    private void jMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSobreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"MAGUISA v1.0", "Sobre Metálicas Maguisa S.L", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuSobreActionPerformed

    private void jMenuItem_NuevaOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NuevaOrdenActionPerformed
        // TODO add your handling code here:
      
        JIntFrmNuevaOrdInterna nuevaOrden = null;
        
        try {
            nuevaOrden = new JIntFrmNuevaOrdInterna();
            //int x=(jPanelPrincipal.getWidth()/2-nuevaOrden.getWidth()/2);
            //int y=(jPanelPrincipal.getHeight()/2-nuevaOrden.getHeight()/2);
        } catch (SQLException ex) {
            Logger.getLogger(MAGUISA.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        jPanelPrincipal.add(nuevaOrden);
        //nuevaOrden.setLocation(x, y);
        nuevaOrden.show();
        try {
            nuevaOrden.setMaximum(true); //Maximizamos el jinternalframe para que ocupe toda la pantalla
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MAGUISA.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem_NuevaOrdenActionPerformed

    private void jMenuItemPaletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPaletsActionPerformed
         // TODO add your handling code here:
      
        JIntFrmCrearPalets nuevoPalet=null;
        try {
            nuevoPalet = new JIntFrmCrearPalets();
            //int x=(jPanelPrincipal.getWidth()/2-nuevaOrden.getWidth()/2);
            //int y=(jPanelPrincipal.getHeight()/2-nuevaOrden.getHeight()/2);
        } catch (SQLException ex) {
            Logger.getLogger(MAGUISA.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        jPanelPrincipal.add(nuevoPalet);
        //nuevaOrden.setLocation(x, y);
        nuevoPalet.show();
        try {
            nuevoPalet.setMaximum(true); //Maximizamos el jinternalframe para que ocupe toda la pantalla
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MAGUISA.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemPaletsActionPerformed

    private void jMenuItem_ArtFichajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ArtFichajesActionPerformed
         // TODO add your handling code here:
      
        JIntFrmArtFichajes fichajes=null;
        fichajes = new JIntFrmArtFichajes();
            
        jPanelPrincipal.add(fichajes);
        //nuevaOrden.setLocation(x, y);
        fichajes.show();
        try {
            fichajes.setMaximum(true); //Maximizamos el jinternalframe para que ocupe toda la pantalla
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MAGUISA.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem_ArtFichajesActionPerformed

    private void jMenuItem_OperariosActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_OperariosActivosActionPerformed
            JIntFrmFichajeOperarios ficOp=null;
        try {
            ficOp = new JIntFrmFichajeOperarios();
            jPanelPrincipal.add(ficOp);
            //nuevaOrden.setLocation(x, y);
            ficOp.show();
            ficOp.setMaximum(true);
        } catch (SQLException ex) {
            Logger.getLogger(MAGUISA.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MAGUISA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem_OperariosActivosActionPerformed

//    private void jMenuItem_OperariosActivos(java.awt.event.ActionEvent evt){                                                      
//        try {                                                      
//            // TODO add your handling code here:
//            
//            JIntFrmFichajeOperarios ficOp=null;
//            ficOp = new JIntFrmFichajeOperarios();
//            
//            jPanelPrincipal.add(ficOp);
//            //nuevaOrden.setLocation(x, y);
//            ficOp.show();
//            try {
//                ficOp.setMaximum(true); //Maximizamos el jinternalframe para que ocupe toda la pantalla
//            } catch (PropertyVetoException ex) {
//                Logger.getLogger(MAGUISA.class.getName()).log(Level.SEVERE, null, ex);
//                JOptionPane.showMessageDialog(this, ex, "ERROR", JOptionPane.ERROR_MESSAGE);
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(MAGUISA.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }      
    
    /**
     * @param args the command line arguments
     */
    public class jPanelPrincipal extends JDesktopPane{
 
       private  Image IMG=new ImageIcon(getClass().getResource("/IMG/maguisa.jpg")).getImage();
 
        public void paintChildren(Graphics g){
            g.drawImage(IMG, 0, 0, getWidth(), getHeight(), this);
            super.paintChildren(g);
        }
    }
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new MAGUISA().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItemPalets;
    private javax.swing.JMenuItem jMenuItem_ArtFichajes;
    private javax.swing.JMenuItem jMenuItem_NuevaOrden;
    private javax.swing.JMenuItem jMenuItem_OperariosActivos;
    private javax.swing.JMenuItem jMenuIxir;
    private javax.swing.JMenu jMenuOrdenes;
    private javax.swing.JMenu jMenuProduccion;
    private javax.swing.JMenuItem jMenuSobre;
    public javax.swing.JDesktopPane jPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
